/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ru.npptmk.common.gui.ruler;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import javax.swing.Icon;
import ru.npptmk.common.gui.ruler.IRulerCoordChange;

/**
 *
 * @author KandybaOA
 */
public class JPanRuler extends javax.swing.JPanel {
    
    
    private IRulerCoordChange listener = null;
    private double wight;
    
    /**шаг слайдера (чем больше цифра, тем выше точность). Например при
     * SliderAccuracy=100, точность будет составлять 1/SliderAccuracy=0.01
     * единицы на линейке*/
    private int SliderAccuracy = 100;
    /**
     * Данный метод позволяет изменить шаг слайдера (чем больше цифра, тем выше
     * точность). Например, при SliderAccuracy=100 точность будет составлять
     * 1/SliderAccuracy=0.01 единицы на линейке
     * @param SliderAccuracy - точность (int)
     */
    public void setSliderAccuracy(int SliderAccuracy) {
        this.SliderAccuracy = SliderAccuracy;
    }
    /** длина линейки (определяет количество основных делений линейки)*/
    private double lengthOfRuler = 10.0;
    /**Максимальное значение на линейке*/
    private final RulerIcon ri = new RulerIcon(lengthOfRuler, this, SliderAccuracy);
    //Значения на которых выставлены ползунки
    private double selectedVal1, selectedVal2;
    
    /**Метод изменяет длину линейки и слайдера, перерисовывая их заново
     * @param lengthOfRuler - длина линейки
     */
    public void setLengthOfRuler(double lengthOfRuler) {
        this.lengthOfRuler = lengthOfRuler;
        ri.setRulerLength(lengthOfRuler);
        jLabel1.repaint();
    }
    
    
    
    public void setWight(double wight) {
        this.wight = wight;
    }

    public void setListener(IRulerCoordChange listener) {
        this.listener = listener;
    }
    
    /**
     * Creates new form jPanelRulerPicture
     */
    public JPanRuler() {
        
        initComponents();
        jLabel1.setIcon(ri);
        
    }

    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}























class RulerIcon implements Icon {

    public boolean flag = false;
    private double width, height, numOfScales;//ширина и высота иконки, желаемое количество делений на линейке
    private double rulerLength;//максимальное значение на линейке
    public void setRulerLength(double rulerLength) {
        this.rulerLength = rulerLength;
    }
    private final JPanRuler jPanRuller;
    private final int SliderAccuracy;  
    
    public RulerIcon(double rulerLength, JPanRuler ruler, int SliderAccuracy) {
        this.rulerLength = rulerLength;
        this.jPanRuller = ruler;
        this.SliderAccuracy=SliderAccuracy;
        flag=false;
    }
    @Override
    public void paintIcon(Component c, Graphics g, int x, int y) { // Величина на которую надо сдвинуть линейку от нижнего края
    
        width = c.getWidth();
        height = c.getHeight();
        g.setColor(Color.yellow);
        g.fillRect(-1, -1, c.getWidth(), c.getHeight()+2);
        g.setColor(Color.BLACK);
        g.drawRect(-1, -1,c.getWidth(), c.getHeight());//  !!!!!!!!!!!!                
        //g.drawRect(0, 0,c.getWidth(), c.getHeight()-1);//  !!!!!!!!!!!!
        //g.clearRect(x, y, (int)width, (int)height);
        //Создаём переменные int для использования в методах draw*****;
        int tempX, tempY1, tempY2;
        /*Math.round(n) — округляет число, которое больше или
        равно аргумента n. Таким образом получаем нужное нам количество делений*/
        numOfScales = Math.round(rulerLength * 10);//cуммарное количество основных  и дополнительных делений линейки
        //координаты для отрисовки делений линейки
        double x1 = x, y1 = y, y2 = y;
        double addToNumOfScales = (Math.round(rulerLength * 10*SliderAccuracy)-Math.round(rulerLength * 10)*SliderAccuracy);; //сколько десятых долей деления нужно отступить в конце. Эта величина необходима, чтобы продлить линейку в конце на величину, меньшую, чем 0.1
        /*количество пикселей между делениями. Вычитаем 16 при расчёте, чтобы
        размер шкалы был меньше размера линейки*/
        double deltaPixel = ((width - 28) / (numOfScales+addToNumOfScales/SliderAccuracy));
        String valOfScaleStr;// переменная, хранящая в себе цифру над делением линейки    
        for (int i = 0; i <= numOfScales; i++) {
            if (i == 0) {
                //Нулевое деление
                x1 = x1 + 13;//сдвигаем первое деление от края линейки               !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                tempX = (int) x1;
                tempY1 = (int) (height / 2);
                tempY2 = (int) (height);
                g.drawLine(tempX, tempY1, tempX, tempY2);
                valOfScaleStr = String.format("%2.0f", (i/10.0));
                //Вычислияем чему равна половина длины строки в пикселях
                int dx = g.getFontMetrics().stringWidth(valOfScaleStr) / 2;
                //подписываем основное деление шкалы соответствующей цифрой
                tempX = (int) (x1 - dx);
                tempY1 = (int) (height / 2 - 2);
                g.drawString(valOfScaleStr, tempX, tempY1);
            } else if (i % 10 == 0) {
                //Рисуем каждое 10 деление кратное единице
                x1 = x1 + deltaPixel;//сдвигаем каждое следующее деление относительно предыдущего
                tempX = (int) x1;
                tempY1 = (int) (height / 2);
                tempY2 = (int) (height);
                g.drawLine(tempX, tempY1, tempX, tempY2);
                valOfScaleStr = String.format("%2.0f", (i/10.0));
                //Вычислияем чему равна половина длины строки в пикселях
                int dx = g.getFontMetrics().stringWidth(valOfScaleStr) / 2;
                //подписываем основное деление шкалы соответствующей цифрой
                tempX = (int) (x1 - dx);
                tempY1 = (int) (height / 2 - 2);
                g.drawString(valOfScaleStr, tempX, tempY1);
            } else if (i % 5 == 0) {
                //рисуем деление шкалы кратное 0.5
                x1 = x1 + deltaPixel;
                tempX = (int) x1;
                tempY1 = (int) (height / 7 * 5);
                tempY2 = (int) (height);
                g.drawLine(tempX, tempY1, tempX, tempY2);
            } else {
                //Рисуем маленькое деление шкалы, кратное 0.1
                x1 = x1 + deltaPixel;
                tempX = (int) x1;
                tempY1 = (int) (height / 7 * 6);
                tempY2 = (int) (height);                
                g.drawLine(tempX, tempY1, tempX, tempY2);
                //Делаем отступ, чтобы правый маркер слайдера мог достать до конца координат
                if(i== numOfScales){
                    
                }
            }
            
            if (!flag) {
                jPanRuller.setWight(width);
                //jPanRuller.getRangeSlider().initRangeSlider();
                flag = true;
            }
        }
    }

    @Override
    public int getIconWidth() {
        return 0;
    }

    @Override
    public int getIconHeight() {
        return 0;
    }

}