/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ru.npptmk.common.gui.ruler;

import javax.swing.JSlider;

/**
 * Класс Ruler представляет из себя JPanel с изображением линейки и
 * двухползунковымслайдером под ней. Значение ползунков слайдера соответствуют 
 * значеням на линейке.
 *
 * Для использования Ruler перетащите его на JPanel или JFrame, отрытые в режиме
 * редактирования "Design" (NetBeans).
 *
 * Для для получения новых значений указателей на линейке при изменении
 * положения указателей на линейке, реализуйте метод public void
 * newValues(double Val1, double Val2); интерфейса IRulerCoordChange.
 *
 * getSelectedVal1() - возвращает значение выбранное левым ползунком слайдера
 * getSelectedVal2() - возвращает значение выбранное правым ползунком слайдера
 * 
 * setLengthOfRuler(double lengthOfRuler) - задаёт значение длины линейки
 *
 * public void setSliderAccuracy(int SliderAccuracy) - Данный метод позволяет
 * изменить шаг слайдера (чем больше цифра, тем выше точность). Например, при
 * SliderAccuracy=100 точность будет составлять 1/SliderAccuracy=0.01 единицы на
 * линейке
 *
 *
 * @author KandybaOA
 */
public class Ruler extends javax.swing.JPanel {

    double lengthOfRuler = 12.0;

    /**
     * Creates new form ruler2
     */
    public Ruler() {
        initComponents();
        jPanRangeSlider1.setLengthOfRuler(lengthOfRuler);
        jPanRuler1.setLengthOfRuler(lengthOfRuler);

    }
    /**Устанавливает длину линейк
     * @param lengthOfRuler - длина линейки*/
    public void setLengthOfRuler(double lengthOfRuler) {
        this.lengthOfRuler = lengthOfRuler;
        jPanRuler1.setLengthOfRuler(lengthOfRuler);
        jPanRangeSlider1.setLengthOfRuler(lengthOfRuler);
    }

    /**
     * Устанавливает listener для слайдера
     * @param listener
     */
    public void setListener(IRulerCoordChange listener) {
        jPanRangeSlider1.setListener(listener);
        jPanRangeSlider1.initRangeSlider();
    }

    /**
     * Возвращает значение выбранное левым ползунком слайдера
     */
    public double getSelectedVal1() {
        return jPanRangeSlider1.getSelectedVal1();
    }

    /**
     * Возвращает значение выбранное правым ползунком слайдера
     */
    public double getSelectedVal2() {
        return jPanRangeSlider1.getSelectedVal2();
    }

    /**
     * Данный метод позволяет изменить шаг слайдера (чем больше цифра, тем выше
     * точность). Например, при SliderAccuracy=100 точность будет составлять
     * 1/SliderAccuracy=0.01 единицы на линейке
     *
     * @param SliderAccuracy - точность (int)
     */
    public void setSliderAccuracy(int SliderAccuracy) {
        jPanRuler1.setSliderAccuracy(SliderAccuracy);
    }

    public void setUpperValue(double val){
        jPanRangeSlider1.setUpperValue(val);
    }
    
    public void setValue(double val){
        jPanRangeSlider1.setValue(val);
    }
    
    public void resetSliders(){
        jPanRangeSlider1.resetSliders();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanRuler1 = new ru.npptmk.common.gui.ruler.JPanRuler();
        jPanRangeSlider1 = new ru.npptmk.common.gui.ruler.JPanRangeSlider();

        jPanRuler1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jPanRuler1ComponentAdded(evt);
            }
        });

        jPanRangeSlider1.setBorder(null);

        jLayeredPane2.setLayer(jPanRuler1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jPanRangeSlider1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addComponent(jPanRangeSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addGap(0, 0, 0))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanRuler1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addGap(0, 96, Short.MAX_VALUE)
                .addComponent(jPanRangeSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanRuler1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLayeredPane2)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLayeredPane2))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanRuler1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jPanRuler1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanRuler1ComponentAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane2;
    private ru.npptmk.common.gui.ruler.JPanRangeSlider jPanRangeSlider1;
    private ru.npptmk.common.gui.ruler.JPanRuler jPanRuler1;
    // End of variables declaration//GEN-END:variables

}
