server:
  port: 8083

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: data-service
          uri: lb://data-service
          predicates:
            - Path=/data/**
          filters:
            - StripPrefix=1
        - id: analysis-service
          uri: lb://analysis-service
          predicates:
            - Path=/analysis/**
          filters:
            - StripPrefix=1
        - id: ui-service
          uri: http://localhost:8082
          predicates:
            - Path=/, /reqvestPage/**, /api/inspection-data, /api/confirm-inspection

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    reactor.netty.http.client: DEBUG
