
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template
# Порт для UI
server.port=8082

# Включить Thymeleaf
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.security.csrf.enabled=false

# Логирование
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

# URL authService
auth.service.url=http://localhost:8081

