
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template
# \u041f\u043e\u0440\u0442 \u0434\u043b\u044f UI
server.port=8082

# \u0412\u043a\u043b\u044e\u0447\u0438\u0442\u044c Thymeleaf
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.security.csrf.enabled=false

# \u041b\u043e\u0433\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435
logging.level.org.springframework.web=DEBUG

